<project name="Lua" default="compile-java">
    <!--
      The compile, build-parser etc targets are all
      defined in the imported file. However, it needs
      a few properties to be defined to work.
    -->
    <property name="lang" value="lua"/>
    <property name="lang.extension" value="lua"/>
    <property name="parser.root" value="Root"/>
    <import file="../ant-common.xml" />
</project>