<project name="Kotlin" default="compile-java">
    <!--
      The compile, build-parser etc targets are all
      defined in the imported file. However, it needs
      the following properties to be defined.
    -->
    <property name="lang" value="kotlin"/>
    <property name="lang.extension" value=".kt"/>
    <property name="parser.root" value="KotlinFile"/>
    <import file="../ant-common.xml" />
</project>