<project name="Kotlin" default="compile">

    <import file="../shared/common.xml" />
    <property name="test.harness" value="KParse"/>

    <target name="init" depends="congo-init">
        <uptodate property="parser.uptodate"
            targetfile="org/parsers/kotlin/KotlinParser.java">
            <srcfiles dir="." includes="*.ccc" />
        </uptodate>
        <property name="grammar.file" value="Kotlin.ccc"/>
        <property name="project.name" value="Kotlin"/>
    </target>
</project>